In [98]:
## Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [99]:
## Importing Data

df = pd.read_csv("Data.csv")
X = df.iloc[:,:3].values 
y = df.iloc[:,-1].values 

In [100]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [101]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [102]:
## Handling Missing Values

#Using Simple Imputer
# from sklearn.impute import SimpleImputer
# si = SimpleImputer(missing_values=np.nan, strategy="mean")
# X[:,1:3] = si.fit_transform(X[:,1:3])

#Using KNNImputer
from sklearn.impute import KNNImputer
ki = KNNImputer(missing_values=np.nan, n_neighbors=2, weights="uniform")
X[:,1:3] = ki.fit_transform(X[:,1:3])


In [103]:
## Encoding Independent Variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

cl = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [0])], remainder='passthrough') #To avoid dummy variable trap we can use drop
X = cl.fit_transform(X)
X


array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 64000.0],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 28.5, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [104]:
## Encoding Target Variable
# cl2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='if_binary'), 0)], remainder='passthrough')
# y = cl.fit_transform(y.reshape(len(y),1)) #Column Tranformer expects a column or matrix form
# y

# Better we can use Label Encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [105]:
## Train-Test Splitting

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)


In [106]:
print(train_X)

[[1.0 0.0 30.0 54000.0]
 [0.0 1.0 28.5 52000.0]
 [0.0 0.0 44.0 72000.0]
 [1.0 0.0 40.0 64000.0]
 [1.0 0.0 50.0 83000.0]
 [0.0 0.0 35.0 58000.0]
 [0.0 1.0 27.0 48000.0]]


In [107]:
print(test_X)

[[0.0 0.0 37.0 67000.0]
 [0.0 1.0 38.0 61000.0]
 [0.0 0.0 48.0 79000.0]]


In [108]:
print(train_y)

[0 0 0 1 0 1 1]


In [109]:
print(test_y)

[1 0 1]


In [110]:
## Feature Scaling(Not always required but is good to do)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#sc.fit(train_X[:,2:])s
train_X[:,2:] = sc.fit_transform(train_X[:,2:])
test_X[:,2:] = sc.transform(test_X[:,2:])

In [111]:
print(train_X)

[[1.0 0.0 -0.7934419644872447 -0.6605419184054852]
 [0.0 1.0 -0.9806586077932238 -0.8350246893050473]
 [0.0 0.0 0.9539133730352276 0.9098030196905738]
 [1.0 0.0 0.4546689908859498 0.21187193609232532]
 [1.0 0.0 1.7027799462591442 1.8694582596381653]
 [0.0 0.0 -0.16938648680064744 -0.311576376606361]
 [0.0 1.0 -1.167875251099203 -1.1839902311041715]]
